'use strict';
// Main. Shared classic-script bindings; startup runs last in main.js.
function reset(selected,preview=false){if(!preview){if(player&&player.runId)bankRun(player);try{let old=JSON.parse(localStorage.getItem('dead-end-survival-v1'));if(old&&old.player)bankRun(old.player);localStorage.removeItem('dead-end-survival-v1')}catch(e){}}gameMode='survival';saveTimer=0;seed=731;t=0;kills=0;collected=0;pending=0;spawnTimer=0;uid=0;zombies=[];drops=[];effects=[];town();player={x:640,y:640,hp:100,max:100,speed:128,damage:23,melee:27,rate:.65,reach:230,cd:0,mc:0,ammo:8,mag:8,reload:0,reloadTime:1.5,level:1,xp:0,next:24,armor:0,regen:0,magnet:65,angle:0,inv:0,damageFlash:0,lastDamage:0,dodgeTime:0,dodgeCooldown:0,dodgeAngle:0,moveAngle:0,stamina:100,maxStamina:100,staminaRegen:8,sneaking:false,visibility:1,sneakSpeed:.56,noise:1,forget:1,ambush:1,talents:{}};caches=[{x:330,y:340},{x:1190,y:550},{x:2160,y:970},{x:1720,y:2150},{x:425,y:2150}].map(c=>({...c,taken:false}));for(let i=0;i<180;i++){let x=range(30,WORLD-30),y=range(30,WORLD-30);if(Math.hypot(x-640,y-640)>240)zombie(x,y)}for(const c of caches)for(let j=0;j<3;j++){let a=range(0,Math.PI*2),r=range(75,160);zombie(c.x+Math.cos(a)*r,c.y+Math.sin(a)*r)}if(isSurvival())initSurvival();player.runId=preview?null:newRunId();player.runScrap=0;player.banked=false;applyLoadout();rebuildSkills();$('#character').style.display=isSurvival()?'block':'none';$('#needs').style.display=isSurvival()?'block':'none';resetInput();syncSneak();mode='play';overlay.style.display='none';$('#game').style.touchAction='none';toast(isSurvival()?'Explore the districts. Open Character → Radio to choose an escape.':'Sneak to hold fire. Buildings block zombie sight.',5)}

function update(dt){for(const a of zombies.concat([player])){a.prevVisualX=a.x;a.prevVisualY=a.y}t+=dt;player.damageFlash=Math.max(0,player.damageFlash-dt);player.dodgeCooldown=Math.max(0,player.dodgeCooldown-dt);if(!isSurvival())player.stamina=Math.min(player.maxStamina,player.stamina+player.staminaRegen*dt);if(isSurvival()){survivalTick(dt);if(mode!=='play')return}toastTime-=dt;if(toastTime<=0)$('#toast').textContent='';player.hp=Math.min(player.max,player.hp+player.regen*dt);player.inv-=dt;player.cd-=dt;player.mc-=dt;let dx=input.x+(keys.d||keys.ArrowRight?1:0)-(keys.a||keys.ArrowLeft?1:0),dy=input.y+(keys.s||keys.ArrowDown?1:0)-(keys.w||keys.ArrowUp?1:0),len=Math.hypot(dx,dy);if(len>1){dx/=len;dy/=len}if(len>.05){let wx=dx/(2*ISOX)+dy/(2*ISOY),wy=dy/(2*ISOY)-dx/(2*ISOX),wl=Math.hypot(wx,wy);wx=wx/wl*Math.min(1,len);wy=wy/wl*Math.min(1,len);player.angle=Math.atan2(wy,wx);player.moveAngle=player.angle;if(player.dodgeTime<=0)move(player,wx*player.speed*(player.sneaking?player.sneakSpeed:1)*dt,wy*player.speed*(player.sneaking?player.sneakSpeed:1)*dt,12)}
if(player.dodgeTime>0){let step=Math.min(dt,player.dodgeTime);player.dodgeTime-=step;for(let i=0;i<4;i++)move(player,Math.cos(player.dodgeAngle)*360*step/4,Math.sin(player.dodgeAngle)*360*step/4,12)}
player.aim=Math.hypot(player.x-player.prevVisualX,player.y-player.prevVisualY)>.04?0:Math.min(1.5,(player.aim||0)+dt);
if(player.reload>0){player.reload-=dt;if(player.reload<=0){let n=isSurvival()?Math.min(player.mag-player.ammo,player.reserve):player.mag;player.ammo=isSurvival()?player.ammo+n:n;if(isSurvival())player.reserve-=n}}
let visible=zombies.filter(z=>z.hp>0&&dist(z,player)<player.reach&&los(player,z)).sort((a,b)=>dist(a,player)-dist(b,player));let target=visible[0];if(target){player.angle=Math.atan2(target.y-player.y,target.x-player.x);if(!player.sneaking&&player.ammo>0&&player.cd<=0&&player.reload<=0){let landed=rand()<hitChance(target,false);if(landed)hurt(target,player.damage);else effects.push({type:'text',x:target.x,y:target.y-25,text:'MISS',life:.65});player.ammo--;player.cd=player.rate;effects.push({type:'shot',x:player.x,y:player.y,tx:target.x+(landed?0:22),ty:target.y+(landed?0:-22),life:.09});makeNoise(player.x,player.y,360*player.noise);if(player.ammo<=0&&(!isSurvival()||player.reserve>0))player.reload=player.reloadTime}let close=visible.filter(z=>z.hp>0&&dist(z,player)<53);if(close.length&&player.mc<=0&&(!isSurvival()||player.stamina>=9)){if(isSurvival())player.stamina-=9;for(const z of (close.slice(0,1+skillRank('cleave')))){let hidden=z.state!=='chase';let landed=rand()<hitChance(z,true);if(landed)hurt(z,player.melee*(hidden?player.ambush:1));else effects.push({type:'text',x:z.x,y:z.y-25,text:'MISS',life:.65});if(z.hp>0){z.state='chase';z.suspicion=1;z.memory=5*player.forget;z.lastX=player.x;z.lastY=player.y}let a=Math.atan2(z.y-player.y,z.x-player.x);if(landed)move(z,Math.cos(a)*20,Math.sin(a)*20,12)}player.mc=.85;effects.push({type:'swing',x:player.x,y:player.y,angle:player.angle,life:.2})}}
for(let i=0;i<zombies.length;i++){let z=zombies[i];if(z.hp<=0)continue;z.hit-=dt;zombieBrain(z,dt);let d=dist(z,player);if(d<25&&player.inv<=0&&player.dodgeTime<=0){receiveDamage(isSurvival()?16:20);player.inv=isSurvival()?.6:.5;if(player.hp<=0){player.hp=0;finish(false);return}}}
separateZombies(dt);zombies=zombies.filter(z=>z.hp>0);for(let i=drops.length-1;i>=0;i--){let d=drops[i],dd=dist(d,player);if(dd<player.magnet&&los(d,player)){let k=Math.min(1,dt*9);d.x+=(player.x-d.x)*k;d.y+=(player.y-d.y)*k}if(dd<19){drops.splice(i,1);if(d.type==='med'){if(isSurvival()){player.meds++;toast('+1 medkit · use in Character')}else{player.hp=Math.min(player.max,player.hp+18);toast('+18 health')}}else{gain(8);if(mode!=='play')return}}}if(drops.length>400)drops.splice(0,drops.length-400);
collectSupplies(dt);
missionTick(dt);if(mode!=='play')return;
spawnTimer-=dt;if(spawnTimer<=0){spawnTimer=Math.max(15,26-t/150);if(zombies.length<190)for(let i=0;i<2;i++){let a=range(0,Math.PI*2),r=range(420,650);let x=player.x+Math.cos(a)*r,y=player.y+Math.sin(a)*r;if(x>20&&x<WORLD-20&&y>20&&y<WORLD-20)zombie(x,y)}}for(const a of zombies.concat([player])){a.visualMoving=Math.hypot(a.x-a.prevVisualX,a.y-a.prevVisualY)>.04;if(a.visualMoving)a.animTime=(a.animTime||0)+dt}for(const e of effects)e.life-=dt;effects=effects.filter(e=>e.life>0)}

function frame(now){let dt=Math.min((now-last)/1000,.04);last=now;if(mode==='play')update(dt);draw();requestAnimationFrame(frame)}


reset('survival',true);mode='title';title();requestAnimationFrame(frame);
