'use strict';
// Survival. Shared classic-script bindings; startup runs last in main.js.
const routes=[{id:'rescue',name:'Helicopter rescue',x:640,y:640,cost:8,duration:180,desc:'Spend 8 parts at the old-town helipad. Wait 3 minutes anywhere, then return for extraction.'},{id:'convoy',name:'Supply convoy',x:4480,y:1280,cost:5,duration:90,desc:'At the eastern depot, deliver 5 parts, 3 rations and 3 water bottles. Remain within 120 units for 90 seconds to depart.'},{id:'broadcast',name:'Emergency broadcast',x:3840,y:4480,cost:12,duration:120,desc:'Repair the southern tower with 12 parts. Accumulate 120 seconds nearby with no zombies within 180 units to secure regional rescue.'}];

function activateRoute(id){let r=routes.find(r=>r.id===id);if(mode!=='radio'||!r||player.mission||dist(player,r)>65||player.parts<r.cost||(id==='convoy'&&(player.rations<3||player.bottles<3)))return;player.parts-=r.cost;if(id==='convoy'){player.rations-=3;player.bottles-=3}player.mission={id,progress:0};player.track=id;saveRun();resumeRun();toast(r.name+' activated',4)}

function missionTick(dt){if(!player.mission)return;let r=routes.find(r=>r.id===player.mission.id);if(r.id==='rescue'||(dist(player,r)<120&&(r.id!=='broadcast'||!zombies.some(z=>z.hp>0&&dist(z,r)<180))))player.mission.progress=Math.min(r.duration,player.mission.progress+dt);if(ready()&&dist(player,r)<65){player.winText=r.name+' completed.';finish(true)}}

function initSurvival(){Object.assign(player,{reserve:40,food:100,water:100,stamina:100,maxStamina:100,staminaRegen:8,rations:2,bottles:2,meds:1,parts:0,day:1,statPoints:2,skillPoints:1,stats:{strength:1,agility:1,endurance:1,perception:1},skills:{},needRate:1,lootBonus:0,mission:null,track:null,aim:0,collectProgress:0,collectIndex:-1,collectLock:0});caches=[];for(let y=0;y<8;y++)for(let x=0;x<8;x++)if((x+y)%3===0)caches.push({x:x*640+330,y:y*640+550,taken:false});player.next=32}

function collectSupplies(dt){player.collectLock=Math.max(0,(player.collectLock||0)-dt);let index=caches.findIndex(c=>!c.taken&&dist(c,player)<35);if(index<0){player.collectProgress=0;player.collectIndex=-1;player.collectMessage='';return}let c=caches[index],moving=Math.hypot(player.x-player.prevVisualX,player.y-player.prevVisualY)>.04,threat=zombies.some(z=>z.hp>0&&dist(z,c)<90&&los(z,c));if(player.collectIndex!==index)player.collectProgress=0;player.collectIndex=index;if(moving||player.dodgeTime>0||player.collectLock>0||threat){player.collectProgress=0;player.collectMessage=threat?'CLEAR NEARBY ZOMBIES':'STAND STILL TO SEARCH';return}player.collectProgress=(player.collectProgress||0)+dt;player.collectMessage='SEARCHING '+Math.min(100,Math.floor(player.collectProgress/player.collectTime*100))+'%';if(player.collectProgress>=player.collectTime){c.taken=true;collected++;player.runScrap=(player.runScrap||0)+12;player.collectProgress=0;player.collectIndex=-1;player.collectMessage='';lootCache()}}

function useSupply(kind){if(!isSurvival()||mode!=='character')return;if(kind==='food'&&player.rations>0&&player.food<100){player.rations--;player.food=Math.min(100,player.food+45)}if(kind==='water'&&player.bottles>0&&player.water<100){player.bottles--;player.water=Math.min(100,player.water+50)}if(kind==='med'&&player.meds>0&&player.hp<player.max){player.meds--;player.hp=Math.min(player.max,player.hp+(player.medHeal||45))}saveRun();characterMenu()}

function lootCache(){player.parts++;player.reserve+=24+player.lootBonus;player.rations++;player.bottles++;if(collected%3===0)player.meds++;if(player.ammo===0&&player.reload<=0)player.reload=player.reloadTime;toast('+1 radio part · ammo, food & water recovered',3);gain(20);saveRun()}

function survivalTick(dt){player.food=Math.max(0,player.food-dt*.13*player.needRate);player.water=Math.max(0,player.water-dt*.20*player.needRate);player.stamina=Math.min(player.maxStamina,player.stamina+dt*player.staminaRegen*(player.food<20?.5:1));if(player.food===0)receiveDamage(dt*.45);if(player.water===0)receiveDamage(dt*.8);if(player.hp<=0){player.hp=0;finish(false);return}let day=1+Math.floor(t/DAY);if(day>player.day){player.day=day;if((day-1)%3===0){caches.forEach(c=>c.taken=false);toast('Supply restock · search locations replenished',5)}else toast('Dawn · supplies remain scarce',3)}saveTimer+=dt;if(saveTimer>=15){saveTimer=0;saveRun()}}
